sudo: required
services:
  - docker

before_install:
  - docker build -t plux96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true plux96/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-856663337060"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
